import Lean.Compiler.LCNF.ToDecl

/-!
# Executable computability check

This module deliberately uses Lean's compiler erasure instead of collecting kernel
axioms: `Classical.choice` inside an erased proof is not an executable dependency.
The implementation is tied to the LCNF APIs in Lean 4.33.1.
-/

open Lean Meta Compiler

namespace RealQuick

private partial def checkExecutable (name : Name) (redirects : NameSet := {}) :
    StateT NameSet MetaM Unit := do
  let env ← getEnv
  let info ← getConstInfo name
  if isNoncomputable env name || isNoncomputable env (mkUnsafeRecName name) then
    throwError "computability check: `{name}` is marked noncomputable (or its recursive implementation is)"
  -- A proof has no executable dependencies, even if its kernel value uses choice.
  if ← isProp info.type then
    return
  if let some impl := getImplementedBy? env name then
    if redirects.contains name then
      throwError "computability check: cyclic implemented_by chain at `{name}`"
    checkExecutable impl (redirects.insert name)
    return
  -- Ordinary recursive calls are fine; implementation-redirection cycles are not.
  if (← get).contains name then
    return
  modify (·.insert name)
  -- Foreign implementations are trusted, just as they are by Lean's compiler.
  if isExtern env name || name == ``Quot.mk || name == ``Quot.lift then
    return
  match info with
  | .ctorInfo .. => return
  | .axiomInfo .. =>
    throwError "computability check: executable axiom `{name}` has no implementation"
  | _ => pure ()
  let decl ← LCNF.CompilerM.run (LCNF.toDecl name)
  decl.value.forCodeM fun code => code.forM fun node => do
    if let .let decl _ := node then
      if let .const dep .. := decl.value then
        -- Generated by `visitQuotLift`; `LetValue.toMono` lowers it to the
        -- identity representation operation. It is not an executable axiom.
        unless dep == ``Quot.lcInv do
          checkExecutable dep

/--
Check that a declaration has an executable implementation according to Lean's
LCNF frontend, throwing a `MetaM` error on failure.

Explicitly `noncomputable` declarations (including recursive implementations) are
rejected even if their bodies happen to compute. Computationally relevant
transitive dependencies are checked after compiler erasure; classical proofs,
proof arguments, and type-only dependencies do not disqualify a definition.
Constructors and unmarked proofs are accepted. Other declarations must be
translatable by `LCNF.toDecl` or have a compiler-provided implementation.

This is a compiler-based check, not a kernel theorem about computability or
termination. It trusts Lean's erasure, `extern`/initialization machinery, and
`implemented_by`/`csimp` semantics. In particular it does not check foreign symbol
availability, replacement equivalence, safety, or termination. It may reject code
that a later optimization could make executable. Imported executable bodies must
be available to the compiler frontend. No code is evaluated or emitted, and
changes to the environment/compiler caches are discarded, including on failure.
-/
def checkComputable (name : Name) : MetaM Unit :=
  withoutModifyingEnv <| (checkExecutable name).run' {}

end RealQuick
