import Lean
import Lean.Compiler.LCNF.ToDecl

import RealQuick.TimeM

open Lean
open Lean Meta Elab Command Compiler
open RealQuick.TimeM

namespace RealQuick.Instrumentation

private partial def checkExecutable (name : Name) (redirects : NameSet := {}) :
    StateT NameSet MetaM Unit := do
  let env ← getEnv
  let info ← getConstInfo name
  if isNoncomputable env name || isNoncomputable env (mkUnsafeRecName name) then
    throwError "computability check: `{name}` is marked noncomputable (or its recursive implementation is)"
  -- A proof has no executable dependencies, even if its kernel value uses choice.
  if ← isProp info.type then
    return
  if let some impl := getImplementedBy? env name then
    if redirects.contains name then
      throwError "computability check: cyclic implemented_by chain at `{name}`"
    checkExecutable impl (redirects.insert name)
    return
  -- Ordinary recursive calls are fine; implementation-redirection cycles are not.
  if (← get).contains name then
    return
  modify (·.insert name)
  -- Foreign implementations are trusted, just as they are by Lean's compiler.
  if isExtern env name || name == ``Quot.mk || name == ``Quot.lift then
    return
  match info with
  | .ctorInfo .. => return
  | .axiomInfo .. =>
    throwError "computability check: executable axiom `{name}` has no implementation"
  | _ => pure ()
  let decl ← LCNF.CompilerM.run (LCNF.toDecl name)
  decl.value.forCodeM fun code => code.forM fun node => do
    if let .let decl _ := node then
      -- Generated by `visitQuotLift`; `LetValue.toMono` lowers it to the
      -- identity representation operation. It is not an executable axiom.
      if let .const dep .. := decl.value then
        unless dep == ``Quot.lcInv do
          checkExecutable dep

/-- Check that a declaration has an executable implementation according to Lean's
LCNF frontend. -/
def checkComputable (name : Name) : MetaM Unit :=
  withoutModifyingEnv <| (checkExecutable name).run' {}

private partial def checkUntimed (ty : Expr) : MetaM Unit := do
  let ty := ty.consumeMData
  if ty.getAppFn.isConstOf ``TimeM then
    throwError "instrumentation expects an untimed source"
  if let some unfolded ← unfoldDefinition? ty then
    unless unfolded == ty do checkUntimed unfolded

/-- Check the first-order data restriction used by the translator. -/
def firstOrderResult (ty : Expr) : MetaM Unit := do
  checkUntimed ty
  let ty ← whnf ty
  if ty.isForall || ty.isSort || (← isProp ty) then
    throwError "instrumentation requires a first-order data result, got{indentExpr ty}"
  unless ← isDefEq (← inferType ty) (.sort (.succ .zero)) do
    throwError "instrumentation currently supports data in Type, not higher universes"

/-- Reject axioms outside the small set permitted by generated instrumentation. -/
def checkAxioms (name : Name) : CoreM Unit := do
  let axioms ← collectAxioms name
  for axiomName in axioms do
    unless [``propext, ``Quot.sound, ``Classical.choice].contains axiomName do
      throwError "unapproved axiom `{axiomName}` in `{name}`"

end RealQuick.Instrumentation
